"""Final Migration1

Revision ID: 000fd9b8027e
Revises: ac364ef6e9e2
Create Date: 2024-06-13 18:35:52.240071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000fd9b8027e'
down_revision: Union[str, None] = 'ac364ef6e9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'profilePhoto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('profilePhoto', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
