"""Added feature of profile photo

Revision ID: 0a4ba47d0d6c
Revises: 597e56431729
Create Date: 2024-06-12 19:57:44.222528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4ba47d0d6c'
down_revision: Union[str, None] = '597e56431729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('profilePhoto', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'profilePhoto')
    # ### end Alembic commands ###
