"""Added feature of profile photo

Revision ID: 35ae2ac79c4e
Revises: 0a4ba47d0d6c
Create Date: 2024-06-12 20:17:22.664055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ae2ac79c4e'
down_revision: Union[str, None] = '0a4ba47d0d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
