"""Added table for profile photo

Revision ID: 661f50562572
Revises: 35ae2ac79c4e
Create Date: 2024-06-12 20:25:32.264240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661f50562572'
down_revision: Union[str, None] = '35ae2ac79c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProfilePhoto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProfilePhoto')
    # ### end Alembic commands ###
