"""Final Migration3

Revision ID: 7f10ac2980f7
Revises: 6c9d27fb2ec7
Create Date: 2024-06-13 20:01:54.955304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f10ac2980f7'
down_revision: Union[str, None] = '6c9d27fb2ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('content_text', sa.Text(), nullable=False))
    op.add_column('Posts', sa.Column('content_file', sa.LargeBinary(), nullable=True))
    op.drop_column('Posts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('Posts', 'content_file')
    op.drop_column('Posts', 'content_text')
    # ### end Alembic commands ###
